# fly.toml app configuration file generated for html-to-text on 2023-07-22T19:32:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "html-to-text"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "5001"

[[mounts]]
  source = "html_to_text_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
